---
docker_enable_pkg_install: true
docker_enable_pip_install: false
docker_enable_configure: true
docker_enable_docker_compose: false
docker_enable_docker_compose_v2: false
docker_enable_docker_python: true

docker_template_daemon_json: "daemon.json.j2"
docker_path_daemon_json: "/etc/docker/daemon.json"

docker_systemd_service: "docker"

docker_package_engine:
  - "docker.io"
docker_package_compose_v1:
  - "docker-compose"
docker_package_compose_v2:
  - "docker-compose-v2"
docker_package_python_docker:
  - "python3-docker"

docker_pip_packages:
  - docker
  # due to bug: https://github.com/jenkinsci/packaging/pull/466/files
  - requests==2.31.0

docker_config:
  log-driver: "json-file"
  log-opts:
    max-size: "150m"
    max-file: "10"
    compress: "true"

docker_registry_credentials: []
#  - registry: "docker.io"
#    username: "almaops"
#    password: "password"
...
