---
- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"

- name: Install extra packages
  package:
    name: "{{ certbot_packages }}"
    state: present

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
